/***********************************************************************/
/*                                                                     */
/*  FILE        :main.c                                                */
/*  DATE        :Fri, Dec 26, 2014                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3069R                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  


#include "iodefine.h"
#include "tcpip_header.h"
//#include "timer.h"
#include "RTL8019AS.h"
#define printf ((int (*)(const char *,...))0x002b86 )




void main(void){
	//const unsigned char myip[4] = {192,168,0,20};
	//const unsigned char myip[4] = {172,16,28,60};
	unsigned char dst_ip[4] = {172,16,28,21};
	unsigned char ntp_ip[4] = {10,3,220,3};
	//unsigned char ntp_ip[4] = {172,16,28,41};
	unsigned char dst_mac[6];
	unsigned short seq[2],ack[2];
	static unsigned short data_len;
	static unsigned char *data;//[100];
	unsigned char tcp_flag;
	unsigned short dstport,srcport;
	unsigned char tcpret;
	unsigned short size,i;
	ether_header eth0;
	//uint32_t i32;
	long i32;
	init_timer();
	NIC_init(eth0.header.src_mac);
	printf("%02x:%02x:%02x:%02x:%02x:%02x\n",eth0.header.src_mac[0],
								eth0.header.src_mac[1],
								eth0.header.src_mac[2],
								eth0.header.src_mac[3],
								eth0.header.src_mac[4],
								eth0.header.src_mac[5]);
								
								
	arp_request(eth0.header.src_mac,myip,ntp_ip,dst_mac);
	printf("%02x:%02x:%02x:%02x:%02x:%02x\n",dst_mac[0],
											dst_mac[1],
											dst_mac[2],
											dst_mac[3],
											dst_mac[4],
											dst_mac[5]);
/*	
	eth0.header.dst_mac[0]=0x00;
	eth0.header.dst_mac[1]=0x26;
	eth0.header.dst_mac[2]=0x2D;
	eth0.header.dst_mac[3]=0x1E;
	eth0.header.dst_mac[4]=0x71;
	eth0.header.dst_mac[5]=0xC3;*/
	
	
	i=0;
	memcpy(sock[i].src_mac,eth0.header.src_mac,6);
	memcpy(sock[i].dst_mac,dst_mac,6);
	memcpy(sock[i].src_ip,myip,4);
	memcpy(sock[i].dst_ip,ntp_ip,4);
	sock[i].src_port=12345;

	while(1){
		delay_ms(1000);
		sntp_get(&sock[i]);
	}
	memset(eth0.header.dst_mac,0xff,6);
	eth0.header.type=0x0800;						
//	arp_request(eth0.header.src_mac,myip,dst_ip,dst_mac);
	seq[0]=0x1234;
	seq[1]=0x5678;
	//ack[0]=0x8756;
	//ack[1]=0x4321;							
//	tcp_send(80,12345,ACK,seq,ack,myip,dst_ip,eth0.header.src_mac,dst_mac,(unsigned char *)"Hello",5);
//	tcp_recv(&srcport,&dstport,&tcp_flag,seq,ack,myip,dst_ip,eth0.header.src_mac,dst_mac,data,&data_len);
//	printf("srcport:%d\ndstport:%d\nflag:%02x\nseq:0x%x%x\nack:0x%x%x\n",srcport,dstport,tcp_flag,seq[0],seq[1],ack[0],ack[1]);
	for(i=0;i<16;i++){
		sock[i].state=CLOSED;
		sock[i].active_flag=0;
		sock[i].close_flag=0;
		memcpy(sock[i].src_mac,eth0.header.src_mac,6);
		sock[i].dst_mac[6];
		memcpy(sock[i].src_ip,myip,4);
		sock[i].dst_ip[4];
		sock[i].src_port=80;
		sock[i].dst_port;
	}
//	long_inc(seq,0xffff);
//	printf("%04x%04x\n",seq[0],seq[1]);
//	while(1);
//	while(1)for(i=0;i<10;i++)eth_send(&eth0,(unsigned char *)&i,2);
//	while(1)tcp_send(80,1234,SYN,seq,0,myip,dst_ip,sock[0].src_mac,dst_mac,(unsigned char *)"Hello",5);
	while(1){
		//printf("seq:%04x%04x\nack:%04x%04x\n",sock[0].seq[0],sock[0].seq[1],sock[0].ack[0],sock[0].ack[1]);
		memset(u_buf.buf,0,1514);
		packet_receive(u_buf.buf);
		arp_reply(eth0.header.src_mac,myip);
		ping_reply(myip,eth0.header.src_mac);
		for(i=0;i<16;i++){
			if(sock[i].state==CLOSED){
				sock[i].active_flag=0;
				sock[i].close_flag=0;
				memcpy(sock[i].src_mac,eth0.header.src_mac,6);
				sock[i].dst_mac[6];
				memcpy(sock[i].src_ip,myip,4);
				sock[i].dst_ip[4];
				sock[i].src_port=80;
				sock[i].dst_port;
			}
			tcp_connection(&sock[i]);
			if(http_reply(&sock[i])==0){
				printf("%d:http:established:port%d\n",i,sock[i].dst_port);
				
			}
		}
	//	tcpret=tcp_recv(&srcport,&dstport,&tcp_flag,seq,ack,dst_ip,myip,dst_mac,eth0.header.src_mac,data,&data_len);
	//	if(tcpret==0) {
	//		printf("\n%u.%u.%u.%u",dst_ip[0],dst_ip[1],dst_ip[2],dst_ip[3]);
	//		printf("\nsrcport:%u\ndstport:%u\nflag:%02x\nseq:0x%x%x\nack:0x%x%x\n",srcport,dstport,tcp_flag,seq[0],seq[1],ack[0],ack[1]);
	//	}
	}
//	printf("arp\n");
//	printf("%d.%d.%d.%d\n",myip[0],myip[1],myip[2],myip[3]);
//	printf("%02x:%02x:%02x:%02x:%02x:%02x\n",dst_mac[0],dst_mac[1],dst_mac[2],dst_mac[3],dst_mac[4],dst_mac[5]);
//	while(1);
}